# This workflow builds a Java project with Maven and caches dependencies
# to improve workflow execution time.
# See: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses third-party actions that are not certified by GitHub
# and are governed by separate terms of service and support.

name: Java CI with Maven - Test_Automation_Framework_Web

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write  # Required for dependency snapshot submission

jobs:
  dependency-submission:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Submit Maven Dependency Snapshot
        if: github.event_name != 'pull_request'
        uses: advanced-security/maven-dependency-tree-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Cucumber tests
        run: mvn clean test

      - name: Upload Cucumber HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-reports/
